spring:
  datasource:
    url: jdbc:mysql://192.168.100.3:3306/xtzn_amm?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: JGOp&7%XPb

mybatis-plus:
  type-aliases-package: com.example.amm.domain.entity
  configuration:
    # mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl